Models/UserLangElement.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Refma.Models
{
    public class UserLangElement
    {
        [Key, Column(Order=0)]
        public string UserId {get; set;}
        [ForeignKey("UserId")]
        public virtual ApplicationUser User {get;set;}

        [Key, Column(Order=1)]
        public int LangElementId { get; set; }
        [ForeignKey("LangElementId")]
        public virtual LangElement LangElement { get; set; }

        public Knowledge Knowledge { get; set; }
    }
}

Controllers/UserLangElementController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Refma.Models;
using Microsoft.AspNet.Identity;
using PagedList;

using System.Web.Configuration;

namespace Refma.Controllers
{

    public class UserLangElementController : Controller
    {
  
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: /UserLangElement/
        public ActionResult Index(string currentFilter, string searchString, int? knowledge, int? page)
        {
            string userId = User.Identity.GetUserId();
            if (userId == null)
            {
                return View(); // return nothing
            }
            
            int defaultPageSize = Int32.Parse(WebConfigurationManager.AppSettings["defaultPageSize"]);

            ApplicationUser currentUser = db.Users.Single(u => u.Id == userId);
            var userlangelements = db.UserLangElements.Include(u => u.LangElement).Include(u => u.User).Where(u => u.UserId == userId);

            if (currentUser.TargetLangId != null)
            {
                userlangelements = userlangelements.Where(u => u.LangElement.LangId == currentUser.TargetLangId);
            }

            ViewBag.TargetLangId = currentUser.TargetLangId;
            ViewBag.CountUnknown = userlangelements.Where(u => u.Knowledge == Knowledge.Unknown).Count();
            ViewBag.CountSeen = userlangelements.Where(u => u.Knowledge == Knowledge.Seen).Count();
            ViewBag.CountDifficult = userlangelements.Where(u => u.Knowledge == Knowledge.Difficult).Count();
            ViewBag.CountKnown = userlangelements.Where(u => u.Knowledge == Knowledge.Known).Count();
            ViewBag.Knowledge = knowledge;

            if (!String.IsNullOrEmpty(searchString))
            {
                userlangelements = userlangelements.Where(s => s.LangElement.Value.Contains(searchString));
            }

            
            if (knowledge.HasValue)
            {
                userlangelements = userlangelements.Where(u => u.Knowledge == (Knowledge)knowledge);
            }

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            int pageNumber = (page ?? 1);

            return View(userlangelements.OrderBy(s => s.LangElement.Value).ToPagedList(pageNumber, defaultPageSize));
        }

        // GET: /UserLangElement/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserLangElement userlangelement = db.UserLangElements.Find(id);
            if (userlangelement == null)
            {
                return HttpNotFound();
            }
            return View(userlangelement);
        }

        // GET: /UserLangElement/Create
        public ActionResult Create()
        {
            ViewBag.LangElementId = new SelectList(db.LangElements, "ID", "Value");
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email");
            return View();
        }

        // POST: /UserLangElement/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserId,LangElementId,Knowledge,Occurency")] UserLangElement userlangelement)
        {
            if (ModelState.IsValid)
            {
                db.UserLangElements.Add(userlangelement);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.LangElementId = new SelectList(db.LangElements, "ID", "Value", userlangelement.LangElementId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email", userlangelement.UserId);
            return View(userlangelement);
        }

        // GET: /UserLangElement/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserLangElement userlangelement = db.UserLangElements.Find(id);
            if (userlangelement == null)
            {
                return HttpNotFound();
            }
            ViewBag.LangElementId = new SelectList(db.LangElements, "ID", "Value", userlangelement.LangElementId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email", userlangelement.UserId);
            return View(userlangelement);
        }

        // POST: /UserLangElement/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserId,LangElementId,Knowledge,Occurency")] UserLangElement userlangelement)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userlangelement).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LangElementId = new SelectList(db.LangElements, "ID", "Value", userlangelement.LangElementId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email", userlangelement.UserId);
            return View(userlangelement);
        }

        // GET: /UserLangElement/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserLangElement userlangelement = db.UserLangElements.Find(id);
            if (userlangelement == null)
            {
                return HttpNotFound();
            }
            return View(userlangelement);
        }

        // POST: /UserLangElement/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            UserLangElement userlangelement = db.UserLangElements.Find(id);
            db.UserLangElements.Remove(userlangelement);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public JsonResult ExportJSON(int? langId, int? knowledge)
        {
            string userId = User.Identity.GetUserId();
            var userlangelements = db.UserLangElements.Include(u => u.LangElement).Where(u => u.UserId == userId);

            if (langId.HasValue)
            {
                userlangelements = userlangelements.Where(u => u.LangElement.LangId == langId);
            }

            if (knowledge.HasValue)
            {
                userlangelements = userlangelements.Where(u => u.Knowledge == (Knowledge)knowledge);
            }

            var jsonObjects = userlangelements.Select(n => new { Language = n.LangElement.Lang.Code, Text = n.LangElement.Value  });

            return Json(jsonObjects, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetUserTargetLanguages()
        {
            string currentUserId = User.Identity.GetUserId();
            var languages = db.WebArticles.Where(u => u.UserId == currentUserId).Select(l => new { l.LangId, l.Lang.ImageSmall }).Distinct();
            return Json(languages.ToList(), JsonRequestBehavior.AllowGet);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/UserLangElement/Create.cshtml
@model Refma.Models.UserLangElement

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserLangElement</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", String.Empty)
                @Html.ValidationMessageFor(model => model.UserId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LangElementId, "LangElementId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LangElementId", String.Empty)
                @Html.ValidationMessageFor(model => model.LangElementId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Knowledge, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Knowledge)
                @Html.ValidationMessageFor(model => model.Knowledge)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Occurency, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Occurency)
                @Html.ValidationMessageFor(model => model.Occurency)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/UserLangElement/Delete.cshtml
@model Refma.Models.UserLangElement

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserLangElement</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LangElement.Value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LangElement.Value)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Knowledge)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Knowledge)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Occurency)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Occurency)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/UserLangElement/Details.cshtml
@model Refma.Models.UserLangElement

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>UserLangElement</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LangElement.Value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LangElement.Value)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Knowledge)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Knowledge)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Occurency)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Occurency)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/UserLangElement/Edit.cshtml
@model Refma.Models.UserLangElement

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserLangElement</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.UserId)

        @Html.HiddenFor(model => model.LangElementId)

        <div class="form-group">
            @Html.LabelFor(model => model.Knowledge, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Knowledge)
                @Html.ValidationMessageFor(model => model.Knowledge)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Occurency, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Occurency)
                @Html.ValidationMessageFor(model => model.Occurency)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/UserLangElement/Index.cshtml
@model PagedList.IPagedList<Refma.Models.UserLangElement>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "My Words";
}

<h2>My Words</h2>

@using (Html.BeginForm("Index", "UserLangElement", FormMethod.Get))
{
    <p>
        Find: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>

}


<table class="table text-center" dir="auto">
    <tr>
        <th class="danger text-center">@Html.ActionLink("Unknown", "Index", new { knowledge = 0 }) <br />  @Html.ActionLink("JSON", "ExportJSON", new { langId = ViewBag.TargetLangId, knowledge = 0 }, new { @type = "button", @class = "btn btn-warning btn-xs" })</th>
        <th class="info text-center">@Html.ActionLink("Seen", "Index", new { knowledge = 1 }) <br />  @Html.ActionLink("JSON", "ExportJSON", new { langId = ViewBag.TargetLangId, knowledge = 1 }, new { @type = "button", @class = "btn btn-warning btn-xs" })</th>
        <th class="warning text-center">@Html.ActionLink("Difficult", "Index", new { knowledge = 2 }) <br />  @Html.ActionLink("JSON", "ExportJSON", new { langId = ViewBag.TargetLangId, knowledge = 2 }, new { @type = "button", @class = "btn btn-warning btn-xs" })</th>
        <th class="success text-center">@Html.ActionLink("Known", "Index", new { knowledge = 3 }) <br />  @Html.ActionLink("JSON", "ExportJSON", new { langId = ViewBag.TargetLangId, knowledge = 3 }, new { @type = "button", @class = "btn btn-warning btn-xs" })</th>
    </tr>
    <tr>
        <td>@ViewBag.CountUnknown</td>
        <td>@ViewBag.CountSeen</td>
        <td>@ViewBag.CountDifficult</td>
        <td>@ViewBag.CountKnown</td>
    </tr>
</table>

<p>

</p>
<table class="table">
    <tr>
        <th>
            Listen
        </th>
        <th>
            Element
        </th>
        <th>
            Knowledge
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr data-eid="@item.LangElementId">

            <td>
                <a onclick="speak('@item.LangElement.Lang.Code','@item.LangElement.Value')" title="Listen" href="javascript:;" class="btn-lg glyphicon glyphicon-play-circle" style="text-decoration: none !important;" />
            </td>
            <td style="vertical-align:middle !important">

                @Html.DisplayFor(modelItem => item.LangElement.Value)
            </td>
            <td style="vertical-align:middle !important">

                @if (item.Knowledge == Refma.Models.Knowledge.Known)
                {
                    <span class="label label-success"> @Html.DisplayFor(modelItem => item.Knowledge) </span>
                }
                else if (item.Knowledge == Refma.Models.Knowledge.Unknown)
                {
                    <span class="label label-default"> @Html.DisplayFor(modelItem => item.Knowledge) </span>
                } 
                else
                {
                    <span class="label label-warning"> @Html.DisplayFor(modelItem => item.Knowledge) </span>
                } 
                
               </td>

            <td style="text-align:right">
                <a title="Request translations" href="@Url.Action("RequestTranslation2", "LangElementTranslation", new { langElementId = item.LangElementId })" class="btn-lg glyphicon glyphicon-cloud" style="text-decoration: none !important;" />
                <a title="Add custom translations" href="@Url.Action("Create", "LangElementTranslation", new { langElementId = item.LangElementId })" class="btn-lg glyphicon glyphicon-plus-sign" style="text-decoration: none !important;" />
                <a title="Show all translations" href="@Url.Action("Index", "LangElementTranslation", new { langElementId = item.LangElementId })" class="btn-lg glyphicon glyphicon-th-list" style="text-decoration: none !important;" />
            </td>
        </tr>
    }

</table>

<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index", new { page, currentFilter = ViewBag.CurrentFilter, knowledge = ViewBag.Knowledge }))