Controllers/LangElementTranslationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Refma.Models;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;

namespace Refma.Controllers
{
    public class LangElementTranslationController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: /LangElementTranslation/
        public ActionResult Index(int? langElementId)
        {
            var translations = db.LangElementTranslations.Include(l => l.Lang).Include(l => l.LangElement);

            if (langElementId.HasValue)
            {   
                string userId = User.Identity.GetUserId();
                ApplicationUser currentUser = db.Users.First(u => u.Id == userId);
                translations = translations.Where(t => t.LangElementId == langElementId).Where(d => d.LangId == currentUser.LangId);
                ViewBag.Itemid = langElementId;
            }

            return View(translations.ToList());
        }

        public ActionResult RequestTranslation2(int langElementId)
        {
            String currentUserId = User.Identity.GetUserId();
            ApplicationUser currentUser = db.Users.Where(u => u.Id == currentUserId).FirstOrDefault();

            LangElement element = db.LangElements.Where(l => l.LangId == currentUser.TargetLangId && l.ID == langElementId).FirstOrDefault();

            GlosbeDictionaryService service = new GlosbeDictionaryService();
            GlosbeResponse response = service.getTranslation(currentUser, element);

            if (response != null)
            {
                foreach (var t in response.tuc)
                {
                    if (t.phrase != null)
                    {
                        if (t.phrase.text != null)
                        {
                            LangElementTranslation newElement = new LangElementTranslation() { LangId = currentUser.LangId, LangElementId = element.ID, Translation = t.phrase.text };
                            db.LangElementTranslations.Add(newElement);
                        }

                    }  
                  
                }
                db.SaveChanges();
            }
            return RedirectToAction("Index", new { langElementId = element.ID });
        }

        public ActionResult RequestTranslation(int langElementId)
        {
            String currentUserId = User.Identity.GetUserId();
            ApplicationUser currentUser = db.Users.Where(u => u.Id == currentUserId).FirstOrDefault();

            LangElement element = db.LangElements.Where(l => l.LangId == currentUser.TargetLangId && l.ID == langElementId).FirstOrDefault();

            PonsDictionaryService service = new PonsDictionaryService();
            List<PonsResponse> responses = service.getTranslation(currentUser, element);

            if (responses != null)
            {
                RawTranslationResponse rawResponse = new RawTranslationResponse() { LangElementId = element.ID, LangId = currentUser.LangId, Provider = "pons" };

                rawResponse.Response = JsonConvert.SerializeObject(responses);
                db.RawTranslationReponses.Add(rawResponse);

                foreach (var item in responses)
                {
                    foreach (var hit in item.Hits)
                    {
                        if (hit.Type == "entry")
                        {
                            foreach (var rom in hit.Roms)
                            {
                                foreach (var arab in rom.Arabs)
                                {
                                    foreach (var trans in arab.Translations)
                                    {
                                        LangElementTranslation newElement = new LangElementTranslation() { LangId = currentUser.LangId, LangElementId = element.ID, Translation = trans.Source + "; " + trans.Target };
                                        db.LangElementTranslations.Add(newElement);
                                    }
                                }
                            }
                        }
                        else if (hit.Type == "translation")
                        {
                            LangElementTranslation newElement = new LangElementTranslation() { LangId = currentUser.LangId, LangElementId = element.ID, Translation = hit.Source + "; "+ hit.Target };
                            db.LangElementTranslations.Add(newElement);
                        }

                    }

                }
                db.SaveChanges();

            }

            return RedirectToAction("Index", new { langElementId = element.ID });

        }

       
        public JsonResult GetTranslations(int langElementId)
        {

            string userId = User.Identity.GetUserId();

            ApplicationUser currentUser = db.Users.Single(u => u.Id == userId);
            var transList = db.LangElementTranslations.Where(u => u.LangElementId == langElementId && u.LangId == currentUser.LangId).Select(p => new  { Value = p.Translation  }).Take(3);

            return Json(transList.ToList(), JsonRequestBehavior.AllowGet);
        }

        // GET: /LangElementTranslation/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LangElementTranslation langelementtranslation = db.LangElementTranslations.Find(id);
            if (langelementtranslation == null)
            {
                return HttpNotFound();
            }
            return View(langelementtranslation);
        }

        // GET: /LangElementTranslation/Create
        public ActionResult Create(int langElementId)
        {
            String currentUserId = User.Identity.GetUserId();
            ApplicationUser currentUser = db.Users.Where(u => u.Id == currentUserId).FirstOrDefault();
            ViewBag.LangId = new SelectList(db.Langs, "ID", "Code", currentUser.LangId); // set user-lang-id!
            ViewBag.LangElementId = new SelectList(db.LangElements.Where(e => e.ID == langElementId), "ID", "Value", langElementId);
            return View();
        }


        // POST: /LangElementTranslation/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,LangElementId,LangId,Translation")] LangElementTranslation langelementtranslation)
        {
            if (ModelState.IsValid)
            {
                db.LangElementTranslations.Add(langelementtranslation);
                db.SaveChanges();

                if (Request.UrlReferrer.PathAndQuery != null)
                {
                    return Redirect(Request.UrlReferrer.PathAndQuery);
                }
                return RedirectToAction("Index");
            }

            ViewBag.LangId = new SelectList(db.Langs, "ID", "Code", langelementtranslation.LangId);
            ViewBag.LangElementId = new SelectList(db.LangElements, "ID", "Value", langelementtranslation.LangElementId);
            return View(langelementtranslation);
        }

        // GET: /LangElementTranslation/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LangElementTranslation langelementtranslation = db.LangElementTranslations.Find(id);
            if (langelementtranslation == null)
            {
                return HttpNotFound();
            }
            ViewBag.LangId = new SelectList(db.Langs, "ID", "Code", langelementtranslation.LangId);
            ViewBag.LangElementId = new SelectList(db.LangElements, "ID", "Value", langelementtranslation.LangElementId);
            return View(langelementtranslation);
        }

        // POST: /LangElementTranslation/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,LangElementId,LangId,Translation")] LangElementTranslation langelementtranslation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(langelementtranslation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LangId = new SelectList(db.Langs, "ID", "Code", langelementtranslation.LangId);
            ViewBag.LangElementId = new SelectList(db.LangElements, "ID", "Value", langelementtranslation.LangElementId);
            return View(langelementtranslation);
        }

        // GET: /LangElementTranslation/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LangElementTranslation langelementtranslation = db.LangElementTranslations.Find(id);
            if (langelementtranslation == null)
            {
                return HttpNotFound();
            }
            return View(langelementtranslation);
        }

        // POST: /LangElementTranslation/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            LangElementTranslation langelementtranslation = db.LangElementTranslations.Find(id);
            db.LangElementTranslations.Remove(langelementtranslation);

Views/LangElementTranslation/Create.cshtml
@model Refma.Models.LangElementTranslation

@{
    ViewBag.Title = "Add translation";
}

<h2>Add new translation</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Add a translation</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.LangElementId, "LangElementId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LangElementId", String.Empty)
                @Html.ValidationMessageFor(model => model.LangElementId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LangId, "LangId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LangId", String.Empty)
                @Html.ValidationMessageFor(model => model.LangId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Translation, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Translation)
                @Html.ValidationMessageFor(model => model.Translation)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/LangElementTranslation/Delete.cshtml
@model Refma.Models.LangElementTranslation

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>LangElementTranslation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Lang.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lang.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LangElement.Value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LangElement.Value)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Translation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Translation)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/LangElementTranslation/Details.cshtml
@model Refma.Models.LangElementTranslation

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>LangElementTranslation</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Lang.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lang.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LangElement.Value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LangElement.Value)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Translation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Translation)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/LangElementTranslation/Edit.cshtml
@model Refma.Models.LangElementTranslation

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>LangElementTranslation</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.LangElementId, "LangElementId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LangElementId", String.Empty)
                @Html.ValidationMessageFor(model => model.LangElementId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LangId, "LangId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LangId", String.Empty)
                @Html.ValidationMessageFor(model => model.LangId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Translation, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Translation)
                @Html.ValidationMessageFor(model => model.Translation)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/LangElementTranslation/Index.cshtml
@model IEnumerable<Refma.Models.LangElementTranslation>

@{
    ViewBag.Title = "Translations";
}

<h2>Translations</h2>

<table class="table">
    <tr>
        <th>
          Source Language
        </th>
        <th>
          Word
        </th>
        <th>
          Target Language
        </th>
        <th>
          Translation
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.LangElement.Lang.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LangElement.Value)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Lang.Name)
        </td>
        <td>
            @Html.Raw(System.Web.HttpUtility.HtmlDecode( item.Translation))<br /><br />
        </td>
        <td>
            <a title="Edit" href="@Url.Action("Edit", "LangElementTranslation", new { langElementId = item.LangElementId })" c class="btn-lg glyphicon glyphicon-pencil" style="text-decoration: none !important;" />
            <a title="Delete" href="@Url.Action("Delete", "LangElementTranslation", new { langElementId = item.LangElementId })" class="btn-lg glyphicon glyphicon-remove" style="text-decoration: none !important;" />
        </td>
    </tr>
}

</table>