Models/LangElement.cs
using System.Data.Entity;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Globalization;
using System;
using System.Collections.Generic;



namespace Refma.Models
{
    public class LangElement
    {
        
        public int ID { get; set; }
      //  [Index("IX_UQ_ELEMENT", Order = 10, IsUnique = true)]
        public int LangId { get; set; }
        [ForeignKey("LangId")]
        public virtual Lang Lang { get; set; }
        [Required, MinLength(1), MaxLength(450)]
    //    [Index("IX_UQ_ELEMENT", Order=20, IsUnique=true)]
        public string Value { get; set; }


        public override bool Equals(object obj)
        {
            if (obj is LangElement)
            {
                LangElement compareObj = (LangElement)obj;
                return this.Value.Equals(compareObj.Value, StringComparison.OrdinalIgnoreCase) &&
                       this.LangId == compareObj.LangId;
                
            }
            return false;
        }

    }

}

Controllers/LangElementController.cs
using System;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Refma.Models;
using System.Web.Configuration;
using PagedList;

namespace Refma.Controllers
{
    public class LangElementController : Controller
    {


        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: /LangElement/
        public ActionResult Index(string langId, string currentFilter, string searchString, int? page)
        {
            int defaultPageSize = Int32.Parse(WebConfigurationManager.AppSettings["defaultPageSize"]);

            var filteredLangElements = from r in db.LangElements select r;

            ViewBag.LangList = (from ul in filteredLangElements
                                select ul.Lang).Distinct();

            if (!String.IsNullOrEmpty(langId))
            {
                int filterLangId = Int32.Parse(langId);
                filteredLangElements = db.LangElements.Where(s => s.LangId == filterLangId);
            }

            if (!String.IsNullOrEmpty(searchString))
            {
                filteredLangElements = filteredLangElements.Where(s => s.Value.Contains(searchString));
            }

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            ViewBag.CurrentLangId = langId;

            int pageNumber = (page ?? 1);

            return View(filteredLangElements.OrderBy(e => e.LangId).ThenBy(e => e.Value).ToPagedList(pageNumber, defaultPageSize));
        }

        // GET: /LangElement/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LangElement langelement = db.LangElements.Find(id);
            if (langelement == null)
            {
                return HttpNotFound();
            }
            return View(langelement);
        }


        // GET: /LangElement/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /LangElement/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,LangId,Value,Occurrency")] LangElement langelement)
        {
            if (ModelState.IsValid)
            {

                db.LangElements.Add(langelement);

                UserLangElement userElement = new UserLangElement();
                userElement.UserId = User.Identity.GetUserId();
                userElement.LangElementId = langelement.ID;

                db.UserLangElements.Add(userElement);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(langelement);
        }

        // GET: /LangElement/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LangElement langelement = db.LangElements.Find(id);
            if (langelement == null)
            {
                return HttpNotFound();
            }
            return View(langelement);
        }

        // POST: /LangElement/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,LangId,Value,Occurrency")] LangElement langelement)
        {
            if (ModelState.IsValid)
            {
                db.Entry(langelement).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(langelement);
        }

        // GET: /LangElement/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LangElement langelement = db.LangElements.Find(id);
            if (langelement == null)
            {
                return HttpNotFound();
            }
            return View(langelement);
        }

        // POST: /LangElement/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            LangElement langelement = db.LangElements.Find(id);
            db.LangElements.Remove(langelement);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        public JsonResult UpdateElementJSON(int elementid, int knowledge)
        {
            string currentUserId = User.Identity.GetUserId();
            UserLangElement ue = db.UserLangElements.Where(u => u.LangElementId == elementid && u.UserId == currentUserId).FirstOrDefault();
            if (ue != null)
            {
                ue.Knowledge = (Knowledge)knowledge;
            }
            else
            {
                ue = new UserLangElement();
                ue.UserId = currentUserId;
                ue.LangElementId = elementid;
                ue.Knowledge = (Knowledge)knowledge;

            }
            db.UserLangElements.AddOrUpdate(ue);
            db.SaveChanges();
            return Json(ue, JsonRequestBehavior.AllowGet);
        }

        public JsonResult ExportJSON(int? langId)
        {

            var langElements = db.LangElements.Include(u => u.Lang);

            if (langId.HasValue)
            {
                langElements = langElements.Where(u => u.LangId == langId);
            }

            var jsonObjects = langElements.Select(n => new { Language = n.Lang.Code, Text = n.Value });

            return Json(jsonObjects, JsonRequestBehavior.AllowGet);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

Views/LangElement/Create.cshtml
@model Refma.Models.LangElement

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>LangElement</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.LangId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LangId)              
                @Html.ValidationMessageFor(model => model.LangId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Value, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Value)
                @Html.ValidationMessageFor(model => model.Value)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Occurrency, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Occurrency)
                @Html.ValidationMessageFor(model => model.Occurrency)
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/LangElement/Delete.cshtml
@model Refma.Models.LangElement

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>LangElement</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Lang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lang.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Value)
        </dd>


    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/LangElement/Details.cshtml
@model Refma.Models.LangElement

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>LangElement</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Lang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lang.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Value)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Occurrency)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Occurrency)
        </dd>


    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/LangElement/Edit.cshtml
@model Refma.Models.LangElement

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>LangElement</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.LangId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LangId)
                @Html.ValidationMessageFor(model => model.LangId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Value, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Value)
                @Html.ValidationMessageFor(model => model.Value)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Occurrency, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Occurrency)
                @Html.ValidationMessageFor(model => model.Occurrency)
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/LangElement/Index.cshtml
@model PagedList.IPagedList<Refma.Models.LangElement>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "All Words";
}

<h2>All Words</h2>


@using (Html.BeginForm("Index", "LangElement", FormMethod.Get))
{
    <p>
        Find: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />

        Language: @Html.DropDownList("langId", new SelectList(ViewBag.LangList, "Id", "Name", ViewBag.CurrentLangId))
        <input type="submit" value="Filter" />
    </p>
}



<table class="table">
    <tr>
        <th>
            Language
        </th>

        <th>
            Value
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td style="vertical-align:middle !important">

                <img src="/images/@item.Lang.ImageBig" style="border-radius: 80% 80% 80% 80%;width: 20px;height:20px" />
                <span> </span>
                @Html.DisplayFor(modelItem => item.Lang.Name)
            </td>

            <td style="vertical-align:middle !important">
                @Html.DisplayFor(modelItem => item.Value)
            </td>
            <td style="text-align:right">
                <a title="Add custom translations" href="@Url.Action("Create", "LangElementTranslation", new { langElementId = item.ID })" class="btn-lg glyphicon glyphicon-plus-sign" style="text-decoration: none !important;" />
                <a title="Show all translations" href="@Url.Action("Index", "LangElementTranslation", new { langElementId = item.ID })" class="btn-lg glyphicon glyphicon-th-list" style="text-decoration: none !important;" />
            </td>
        </tr>
    }

</table>

<br />
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, langId = ViewBag.CurrentLangId, currentFilter = ViewBag.CurrentFilter }))