Models/WebArticle.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.ComponentModel.DataAnnotations.Schema;

namespace Refma.Models
{
    public class WebArticle
    {
        public int ID { get; set; }
        public int LangId { get; set; }
        [ForeignKey("LangId")]
        public virtual Lang Lang { get; set; }
        public String Title { get; set; }
        public String URL { get; set; }
        public String PlainText { get; set; }
        public string UserId { get; set; }
        public double? PercentageKnown { get; set; }
        [ForeignKey("UserId")]
        public virtual ApplicationUser User { get; set; }
    }


}

Controllers/WebArticlesController.cs
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Refma.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Text.RegularExpressions;
using System.Data.Entity.Validation;
using System.Diagnostics;
using System.Web.Configuration;
using PagedList;
using System.ComponentModel.DataAnnotations;

namespace Refma.Controllers
{
    public class WebArticlesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: /WebArticles/
        public ActionResult Index(string currentFilter, string searchString, int? page)
        {

            string userId = User.Identity.GetUserId();
            if (userId != null)
            {
                int defaultPageSize = Int32.Parse(WebConfigurationManager.AppSettings["defaultPageSize"]);

                ApplicationUser currentUser = db.Users.First(u => u.Id == userId);
                ViewBag.LangCode = currentUser.TargetLang.Code;


                var userWebArticles = from e in db.WebArticles
                                      where e.UserId == userId && e.LangId == currentUser.TargetLangId
                                      // orderby e.ID descending
                                      select e;

                if (!String.IsNullOrEmpty(searchString))
                {
                    userWebArticles = userWebArticles.Where(s => s.Title.Contains(searchString));
                }

                if (searchString != null)
                {
                    page = 1;
                }
                else
                {
                    searchString = currentFilter;
                }

                ViewBag.CurrentFilter = searchString;

                int pageNumber = (page ?? 1);

                return View(userWebArticles.OrderByDescending(u => u.ID).ToPagedList(pageNumber, defaultPageSize));


            }
            return View();// show nothing
        }

        public class FrequencyModel {
            public string LangName;
            public int LangElementId;
            public string LangElementValue;
            public int Occurences;
        }

        public ActionResult Dashboard()
        {

            string userId = User.Identity.GetUserId();
            if (userId != null)
            {

                ApplicationUser currentUser = db.Users.First(u => u.Id == userId);

                int userTargetCode = currentUser.TargetLang.ID;

                var freqList = from w in db.WebArticleElements
                               join e in db.LangElements on w.LangElementId equals e.ID into temp
                            
                               from t in temp.DefaultIfEmpty()
                               where t.LangId.Equals(userTargetCode)
                               group t by new { t.Lang.Name, t.Value, w.LangElementId } into g
                               select new FrequencyModel
                               {
                                   LangName = g.Key.Name,
                                   LangElementId = g.Key.LangElementId,
                                   LangElementValue = g.Key.Value,
                                   Occurences = g.Count()
                               };


                return View(freqList.OrderByDescending(f => f.Occurences).Take(500).ToList());
            }

            return View();
        }

        public ActionResult Read(int? id) 
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            db.Database.Log = s => System.Diagnostics.Debug.WriteLine(s);
            WebArticle webarticle = db.WebArticles.Find(id);
            if (webarticle == null)
            {
                return HttpNotFound();
            }

            string currentUserId = User.Identity.GetUserId();
            ApplicationUser currentUser = db.Users.Where(u => u.Id == currentUserId).FirstOrDefault();

            ArticleDecorator decorator = new ArticleDecorator(webarticle);
            List<ViewArticleElement> viewElements = decorator.GetAllViewElements();



            ViewBag.ViewElements = viewElements;

            return View(webarticle);
        }

        // GET: /WebArticles/Create
        public ActionResult Create()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }

            string userId = User.Identity.GetUserId();
            ApplicationUser currentUser = db.Users.First(u => u.Id == userId);
            ViewBag.CurrentTargetLangId = currentUser.TargetLangId;

            List<Lang> langList;
            langList = db.Langs.ToList<Lang>();
            ViewBag.LangList = langList;

            return View();
        }

        // POST: /WebArticles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,LangId,Title,URL,PlainText")] WebArticle webarticle)
        {
            if (ModelState.IsValid)
            {
                string userId = User.Identity.GetUserId();
                webarticle.UserId = userId;

                if (webarticle.URL != null)
                {
                    // first, save article to get Id
                    string title;
                    webarticle.PlainText = WebtextExtractor.ExtractTextOnly(webarticle.URL, out title);
                    webarticle.Title = System.Web.HttpUtility.HtmlDecode(webarticle.Title + title);

                    if (webarticle.Title == null)
                    {
                        webarticle.Title = webarticle.URL;
                    }

                    db.WebArticles.Add(webarticle);
                    db.SaveChanges();
                    // end saving article, id known nown

                    UpdateOrInsertBaseLangElements(webarticle);
                }
                else if (webarticle.PlainText != null)
                {
                    // manuall text
                    db.WebArticles.Add(webarticle);
                    db.SaveChanges();
                    UpdateOrInsertBaseLangElements(webarticle);

                }
                return RedirectToAction("Read", new { id = webarticle.ID });
            }
            return View(webarticle);
        }

        private void UpdateOrInsertBaseLangElements(WebArticle webarticle)
        {
            // ...update insert or update base elements

            // split text into "word"-strings to get distinct "words" of article without special characters likes spaces, line feeds etc.
            string[] splitStrings = Regex.Split(webarticle.PlainText.Replace("\n", String.Empty), SpecialCharactersClass.getNonLetterPattern()).Distinct().Where(s => s.Length >= 1).ToArray();

            // create new list and transfer plain "word" strings to LangElement-Objects
            List<LangElement> articleElements = new List<LangElement>(splitStrings.Length);
            for (int i = 0; i < splitStrings.Length; i++)
            {

                string currentString = splitStrings[i];
                // check if word exists already in database
                LangElement foundElement = db.LangElements.Where(l => l.Value.Equals(currentString, StringComparison.OrdinalIgnoreCase) && l.LangId == webarticle.LangId).FirstOrDefault();
                if (foundElement == null)
                {
                    // not found, add word to database
                    foundElement = new LangElement() { LangId = webarticle.LangId, Value = currentString };
                    db.LangElements.Add(foundElement);
                    db.SaveChanges();
                }

                // link this word also to article to reduce loading times when reading
                db.WebArticleElements.AddOrUpdate(new WebArticleElement() { WebArticleId = webarticle.ID, LangElementId = foundElement.ID });
                db.SaveChanges();

            }
        }


        // GET: /WebArticles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WebArticle webarticle = db.WebArticles.Find(id);
            if (webarticle == null)
            {
                return HttpNotFound();
            }
            return View(webarticle);
        }

        // POST: /WebArticles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            WebArticle webarticle = db.WebArticles.Find(id);
            db.WebArticles.Remove(webarticle);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public JsonResult UpdatePercentage(int id, double percentage)
        {
            string currentUserId = User.Identity.GetUserId();
            WebArticle a = db.WebArticles.Where(u => u.ID == id && u.UserId == currentUserId).FirstOrDefault();

            if (a != null)
            {
                a.PercentageKnown = percentage;
            };
            db.WebArticles.AddOrUpdate(a);
            db.SaveChanges();
            return Json(a.PercentageKnown, JsonRequestBehavior.AllowGet);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

Views/WebArticles/Create.cshtml
@model Refma.Models.WebArticle

@{
    ViewBag.Title = "Add article";
}

<h2>Add a new article</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Article</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Lang, new { @class = "control-label  col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.LangId, new SelectList(ViewBag.LangList, "Id", "Name", ViewBag.CurrentTargetLangId), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LangId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.URL, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.URL, htmlAttributes: new { style = "width: 100%; max-width: 100%;" })
                @Html.ValidationMessageFor(model => model.URL)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Title, htmlAttributes: new { style = "width: 100%; max-width: 100%;" })
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PlainText, new { @class = "control-label col-md-2" })
           
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.PlainText, htmlAttributes: new { style = "width: 100%; max-width: 100%;" })
                @Html.ValidationMessageFor(model => model.PlainText)
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/WebArticles/Dashboard.cshtml
@model IEnumerable<Refma.Controllers.WebArticlesController.FrequencyModel>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>Dashboard</h2>
<table class="table-striped" >
    <tr>
        <th>
           Wort
        </th>
        <th>
           Occures in N articles
        </th>
    </tr>
    

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.LangElementValue)
            </td>
            <td>
               @Html.DisplayFor(modelItem => item.Occurences)
            </td>
        </tr>
    }

</table>

Views/WebArticles/Delete.cshtml
@model Refma.Models.WebArticle

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>WebArticle</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Lang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lang.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.URL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.URL)
        </dd>


    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/WebArticles/Index.cshtml
@model PagedList.IPagedList<Refma.Models.WebArticle>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "My Articles";
}

<h2>My Articles</h2>

@using (Html.BeginForm("Index", "WebArticles", FormMethod.Get))
{
    <p>
        Find: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>

}

<p>
    @Html.ActionLink("Add new article", "Create", new { }, new { @type = "button", @class = "btn btn-default" })
</p>

<table class="table" dir="auto" lang="@ViewBag.LangCode">


    @foreach (var item in Model)
    {
        <tr>
            <td style="vertical-align:middle !important">

                <b>@Html.ActionLink(item.Title, "Read", new { id = item.ID }) </b>
                @if (item.PercentageKnown.HasValue)
                {
                    if (item.PercentageKnown < 85)
                    {
                        <span class="label label-warning">@item.PercentageKnown%</span>
                    }
                    else if (item.PercentageKnown < 70)
                    {
                        <span class="label label-danger">@item.PercentageKnown%</span>
                    }
                    else
                    {
                        <span class="label label-success">@item.PercentageKnown%</span>
                    }
                }
            </td>
            <td style="text-align:right">

                @if (item.URL != null)
                {

                    <a title="Source" href="@Html.DisplayFor(modelItem => item.URL)" class="btn-lg glyphicon glyphicon-link" style="text-decoration: none !important;">
                        <span class="sr-only">Source</span>
                    </a>

                }

                <a title="Delete" href="@Url.Action("Delete", new { id = item.ID })" class="btn-lg glyphicon glyphicon-remove" style="text-decoration: none !important;">
                    <span class="sr-only">Delete</span>
                </a>
            </td>
        </tr>
    }

</table>

Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index", new { page, currentFilter = ViewBag.CurrentFilter }))

Views/WebArticles/Read.cshtml
@using Refma.Models
@model Refma.Models.WebArticle
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    ViewBag.Title = "Read Article";
}
@section CustomJavascript {
    <script type="text/javascript">

        var currentLang = @Html.Raw(Json.Encode(Model.Lang.Code));
        var currentArticleID = @Model.ID;

        $(document).ready(function () {

            getPercentageKnown();

            function getPercentageKnown() {
                var totalWords = $('span').length;
                var numItemsKnown = $('.Known').length;
                var percentageKnown = numItemsKnown * 100 / totalWords;

                $('div#percentage').html(Math.round(percentageKnown) + "% words known in this article.");

                savePercentage(currentArticleID, Math.round(percentageKnown));
            }

            function updateElement(eid, k) {
                $.ajax({
                    type: "POST",
                    url: '/LangElement/UpdateElementJSON',
                    data: { elementid: eid, knowledge: k },
                    success: function () {
                        // do not do anything
                    }
                });
            }

            function savePercentage(aid, p) {
                $.ajax({
                    type: "POST",
                    url: '/WebArticles/UpdatePercentage',
                    data: { id: aid, percentage: p },
                    success: function () {
                        // do not do anything
                    }
                });
            }

            function retrieveTranslations(eid) {
                $.ajax({
                    type: "POST",
                    url: '/LangElementTranslation/GetTranslations',
                    data: { langElementId: eid },
                    datatype: "json",
                    success: function (data) {

                        
                        $.each(data, function(index) {

                            
                            $('#'+eid).append("<p>"+  data[index].Value + "</p>");
                        });
                    }
                });
               
            }

            function changeClassForElement(eid, new1) {
                $('span[data-eid="' + eid + '"]').each(function () {
                    $(this).removeClass().addClass(new1);
                });
            }


            $('body').on('click', 'button#setUnknown', function () {
                var eid = $(this).attr("data-eid");
                updateElement(eid, 0);
                changeClassForElement(eid, "Unknown");
                getPercentageKnown();
            });

            $('body').on('click', 'button#setSeen', function () {
                var eid = $(this).attr("data-eid");
                updateElement(eid, 1);
                changeClassForElement(eid, "Seen");
                getPercentageKnown();
            });

            $('body').on('click', 'button#setHard', function () {
                var eid = $(this).attr("data-eid");

                updateElement(eid, 2);
                changeClassForElement(eid, "Difficult");
                getPercentageKnown();
            });

            $('body').on('click', 'button#setKnown', function () {
                var eid = $(this).attr("data-eid");

                updateElement(eid, 3);
                changeClassForElement(eid, "Known");
                getPercentageKnown();
            });

            $('span').popover({
                html: 'true',
                trigger: 'focus',
                placement: 'bottom',
                container: 'body',
                title: function () {
                    return $(this).html() +  " <span class=\"glyphicon glyphicon-play-circle\" onclick=\"speak('"+currentLang +"','" + $(this).html() + "')\"></span>" ;
                },
                content: function () {

                    
                    retrieveTranslations($(this).attr('data-eid'));
                    return '<div id="' + $(this).attr('data-eid') + '"></div>'+
                        '<button id="setUnknown" type="button" class="btn btn-unknown" data-eid="' + $(this).attr('data-eid') + '">0</button>' +
                            '<button id="setSeen" type="button" class="btn btn-seen" data-eid="' + $(this).attr('data-eid') + '">1</button>' +
                            '<button id="setHard" type="button" class="btn btn-hard" data-eid="' + $(this).attr('data-eid') + '">2</button>' +
                              '<button id="setKnown" type="button" class="btn btn-known" data-eid="' + $(this).attr('data-eid') + '">3</button>';
                }
            });
        });

    </script>
}


<div dir="auto" lang="@Model.Lang.Code">
    <div style="display: inline-block; width: 30px; height: 30px;  border-radius: 15px; -webkit-border-radius: 15px; -moz-border-radius: 15px; background: url(/images/@Model.Lang.ImageSmall) no-repeat; background-size: 30px 30px;"></div>

    <h2>@Html.DisplayFor(model => model.Title)</h2>

    <span class="glyphicon glyphicon-play-circle" onclick="speak('@Model.Lang.Code','@Model.Title')"></span>

    <div id="percentage"></div>
    <hr />


    <div class="main-article">
        @foreach (var el in (List<ViewArticleElement>)ViewBag.ViewElements)
        {

            if (@el.IsNotAWord)
            {
                if (@el.Value.Contains("\n"))
                {

                    <br><br>
                }
                else
                {
                    @el.Value
                }
            }
            else
            {

                var dataContent = "";
                if (el.Translations.Count > 0)
                {
                    dataContent += "<table class='table'>";
                    foreach (var item in el.Translations)
                    {
                        dataContent += "<tr><td>" + item + "</tr></td>";
                    }
                    dataContent += "</table>";

                }
 
                <span data-eid="@el.LangElementId" translation="@dataContent" tabindex="0" class="word @el.Knowledge">@el.Value</span>
            }
        }
    </div>

    <br />

    <p>
        @Html.ActionLink("Back to List", "Index")
    </p>

</div>